run:
  #modules-download-mode: readonly
linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocognit:
    min-complexity: 30
  cyclop:
    max-complexity: 30
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  testifylint:
    disable:
      - require-error
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/beorn7/perks/quantile
          - github.com/getsentry/sentry-go
          - github.com/gin-gonic/gin
          - github.com/nikandfor/cli
          - github.com/nikandfor/quantile
          - github.com/opentracing/opentracing-go
          - github.com/prometheus/client_golang
          - github.com/prometheus/client_model
          - github.com/stretchr/testify
          - go.opentelemetry.io/otel
          - golang.org/x
          - gopkg.in/fsnotify.v1
          - tlog.app/go/errors
          - tlog.app/go/loc
          - tlog.app/go/tlog
  misspell:
  lll:
    line-length: 170
  goimports:
    local-prefixes: github.com/nikandfor/tlog
  prealloc:
    simple: true
    for-loops: true
  gocritic:
    enabled-tags:
      - experimental
      - performance
      - style
    disabled-checks:
      - appendAssign
      - builtinShadow
      - commentedOutCode
      - octalLiteral
      - unnamedResult
      - whyNoLint
      - yodaStyleExpr

linters:
  enable-all: true
  disable:
    - err113
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - godox
    - golint
    - gomnd
    - mnd
    - nakedret
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - testifylint # nice linter, but doesn't follow settings
    - testpackage
    - thelper
    - unparam
    - varnamelen
    - wsl
